---
- name: Check if executable exist
  ansible.builtin.stat:
    path: "/usr/sbin/snmptrapd"
  register: snmptrapd_binary

- name: "Install tasks"
  when: not snmptrapd_binary.stat.exists
  block:
    - name: Install required packages
      ansible.builtin.package:
        name: [snmptrapd, rsync]
        state: present

    - name: Create required folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "/etc/systemd/system/snmptrapd.service.d"
        - "{{ snmptrapd_logdir }}"

    - name: Start and enable snmptrapd service
      ansible.builtin.service:
        name: snmptrapd
        state: started
        enabled: true

#- name: Synchronise mibs
#  synchronize:
#    src: mibs
#    dest: /var/lib/
- name: Synchronise mibs
  ansible.builtin.copy:
    src: mibs
    dest: /var/lib/
    mode: '0640'

- name: Create systemd override
  ansible.builtin.template:
    src: snmptrapd_override.conf
    dest: "/etc/systemd/system/snmptrapd.service.d/override.conf"
    mode: 0644
  notify:
    - reload daemon
    - restart snmptrapd

- name: Create config file
  ansible.builtin.template:
    src: snmptrapd.conf
    dest: "/etc/snmp/snmptrapd.conf"
    mode: 0644
  notify:
    - restart snmptrapd
